### ISSUE TITLE
✨ Create Layout for Login/Signup Screens

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Frontend#2]
Your task is to create the screens for the Login and Signup screens of the app. The pages should be user-friendly, visually appealing, and responsive.

Requirements:
-->Login Page:
Fields for Email/Username and Password.
A Login button.
A Forgot Password link.
An option to Switch to Signup page (like a "Don't have an account? Signup here" text).

-->Signup Page:
Fields for Name, Email, and Password.
A Signup button.
An option to Switch to Login page (like a "Already have an account? Login here" text).

For reference, please check this Figma design [figma](https://www.figma.com/design/cVyAkllTJq5IZfjSSWnFc5/Untitled?node-id=0-1&t=7ss4xar4BiDL87tG-1) or attached image.

![image](https://github.com/user-attachments/assets/34d8d7d0-6738-43a7-a4e4-fa48a3df5a84)

**Comment by official-ashutosh** [comment]
claim

**Comment by aashray374** [comment]
@swarupn17 whats your progress?

**Comment by swarupn17** [comment]
@aashray374 Working on it, will make a PR tomorrow.

**Comment by oopshwet** [comment]
claim
