### ISSUE TITLE
🤔Create Forgot Password Screens

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Frontend#3]
Your task is to create the screens for the OTP verification Screen and Password Updation Screen. Both screens should be responsive 📱.
For reference, please check the app's Figma design [figma](https://www.figma.com/design/cVyAkllTJq5IZfjSSWnFc5/Untitled?node-id=0-1&t=7ss4xar4BiDL87tG-1) or attached image.

![image](https://github.com/user-attachments/assets/844de42b-99fa-4907-bed9-0e7e9d13669f)

**Comment by Athting** [comment]
claim/

**Comment by official-ashutosh** [comment]
Claim/

**Comment by sanjitha006** [comment]
claim

**Comment by aashray374** [comment]
@Athting whats your progress?

**Comment by Navigam1108** [comment]
Claim

**Comment by aashray374** [comment]
@Navigam1108 whats your progress

**Comment by Navigam1108** [comment]
> @Navigam1108 whats your progress

WIP.

**Comment by Navigam1108** [comment]
claim
