### ISSUE TITLE
Make first impression count

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Frontend#71]
Your task is to create a splash screen for the app. The splash screen should meet the following requirements:

It should have a #0A0D16 color background with the text "WordOut" displayed on it.
The text should animate during the transition between screens.
Meanwhile, check for a token in shared preferences.
If the token is not null, navigate to the Home Screen.
Otherwise, navigate to the Sign-Up Screen.

if possible attach a short video of the transition to help me merge PR effortlessly.

**Comment by Navigam1108** [comment]
claim

**Comment by shubhranka** [comment]
claim

**Comment by aashray374** [comment]
@Navigam1108 whats your progress?

**Comment by Navigam1108** [comment]
> @Navigam1108 whats your progress?
> 

Electricity issues, laptop is discharged. It will come by 5. Task will be finished EOD

**Comment by saipy10** [comment]
I have solved the issue as per the description of issue

https://github.com/user-attachments/assets/4ddf8506-2e26-43b0-97f3-56b68694afd0
