### ISSUE TITLE
Logic for forgot password

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Frontend#72]
As the Forgot Password screens are being developed in issue #3, your task is to implement the backend logic for these screens in a file named forgot_password_services.dart. This file will contain static methods to handle the forgot password functionality.

Requirements
File Structure:

Create a file named forgot_password_services.dart in the appropriate folder (e.g., services or utils).
Static Methods:

Write static methods for the following functionalities:
Send Verification Code: Sends a 6-digit code to the user's email.
Verify Code: Validates the entered code.
Reset Password: Updates the user's password after verification.
API Integration:

Use HTTP package to call the backend APIs.
Ensure proper error handling and user feedback.

for backend visit [WordOut-Backend](https://github.com/opencodeiiita/WordOut-Backend)

**Comment by Snehalgupta-07** [comment]
Claim

**Comment by Navigam1108** [comment]
claim

**Comment by poonam17122004** [comment]
claim

**Comment by Snehalgupta-07** [comment]
@aashray374 I have unassigned it you can assign it to someone else.

**Comment by HGRgamer** [comment]
claim
