### ISSUE TITLE
Implement the Search Screen

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Frontend#78]
Your task is to implement the design of user search screen which will be used to send friend requests to differernt users fo the app.

![image](https://github.com/user-attachments/assets/f0b42cf7-299f-4f73-b704-9bd44d160117)

for design you can visit the [figma](https://www.figma.com/design/cVyAkllTJq5IZfjSSWnFc5/Untitled?node-id=0-1&t=1WB1Blz1dEFr2UaX-1)

**Comment by HGRgamer** [comment]
claim

**Comment by Navigam1108** [comment]
Claim
