### ISSUE TITLE
Implement the error and success screens

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Frontend#79]
Your task is to design and implement dedicated Error and Success screens for the application. These screens will enhance user experience by providing clear feedback when actions fail or succeed.

![image](https://github.com/user-attachments/assets/b3fea076-03d6-4e20-9e12-8b6269d87a57)

for design you can visit the [figma](https://www.figma.com/design/cVyAkllTJq5IZfjSSWnFc5/Untitled?node-id=0-1&t=1WB1Blz1dEFr2UaX-1)

**Comment by Navigam1108** [comment]
Claim

**Comment by HGRgamer** [comment]
claim

**Comment by PriyamJChakrabarty** [comment]
claim

**Comment by PriyamJChakrabarty** [comment]
Bro 1 week se zyada ho gaya @aashray374 assign it to me
